# Generated by Django 3.2.5 on 2022-05-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dda_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dda_db',
            old_name='rackToint',
            new_name='rackTotCnt',
        ),
        migrations.AlterField(
            model_name='dda_db',
            name='stationName',
            field=models.CharField(max_length=64),
        ),
    ]
